#!/bin/sh

echo 0 > /sync-initial

# Sync from /mnt/host via remapped /mnt/bind to /mnt/app.

bindfs_options="--map=$HOST_UID/$APP_UID:@$HOST_GID/@$APP_GID /sync-host /sync-bind"
bindfs $bindfs_options || (echo "Failed to bindfs $line" && exit 1)

# Sync directly on start.
unison_options="-batch -owner -group -times $UNISON_OPTIONS"
sh -c "unison /sync-bind /sync-app $unison_options"
echo 1 > /sync-initial

# Watch if configured.
if [ "$UNISON_WATCH" -eq 1 ]; then
    unison_options="-repeat watch $unison_options"
    sh -c "unison /sync-bind /sync-app $unison_options"
fi
